@catalogUrl = http://localhost:5000
@basketUrl = http://localhost:5001


### Update catalog
POST {{catalogUrl}}/api/catalog
Content-Type: application/json
{
    "description": "CatalogItemDesc",
    "name": "CatalogItemName",
    "price": 200.00
}

### Update basket
POST {{{basketUrl}}}/basket
Content-Type: application/json
{
    "buyerid": "5d87812aa5227d4365f9b71e",
    "items": 
    [{
        "id": "5d878134541019177ddda058",
        "productid": "5d8782121565fb33f456ae89",
        "productname": "Smyczka",
        "unitprice": 25.00,
        "oldunitprice": 50.00,
        "quantity": 1
    },
    {
        "id": "5d87813ddb7715777253fcc3",
        "productid": "5d8782911565fb33f456ae8b",
        "productname": "Karma",
        "unitprice": 50.00,
        "oldunitprice": 60.00,
        "quantity": 2
    }]
}



















































































































































































































































































































































































































































































































































    
}